version: "3.8"

services:
  solidity-analyzer:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: solidity-analyzer
    ports:
      - "5001:5000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FUZZ_API_KEY=${FUZZ_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
