version: "3.8"

services:
  solidity-analyzer:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: solidity-analyzer
    ports:
      - "${API_PORT:-5001}:5000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - FLASK_ENV=development
      - PORT=5000
    restart: unless-stopped
